# Generated by Django 5.0.6 on 2024-05-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisApply',
            fields=[
                ('thesis_apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_students', models.ManyToManyField(blank=True, to='student.student')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
