# Generated by Django 5.0.6 on 2024-05-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisapply',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/'),
        ),
    ]
