# Generated by Django 5.0.6 on 2024-05-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0002_thesisapply_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisapply',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
