# Generated by Django 5.0.6 on 2024-05-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0004_remove_thesisapply_applied_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisapply',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
