# Generated by Django 5.0.6 on 2024-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0005_thesisapply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisapply',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
