# Generated by Django 5.0.6 on 2024-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0006_thesisapply_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisapply',
            name='supervisor_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thesisapply',
            name='unit_co_approval',
            field=models.BooleanField(default=False),
        ),
    ]
