# Generated by Django 5.0.6 on 2024-05-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0007_thesisapply_supervisor_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisapply',
            old_name='applied_students',
            new_name='applied_student',
        ),
    ]
