# Generated by Django 5.0.6 on 2024-05-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0008_rename_applied_students_thesisapply_applied_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisapply',
            old_name='unit_co_approval',
            new_name='unit_co_checked',
        ),
    ]
