# Generated by Django 5.0.6 on 2024-05-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0009_rename_unit_co_approval_thesisapply_unit_co_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisapply',
            name='supervisor_checked',
            field=models.BooleanField(default=False),
        ),
    ]
