# Generated by Django 5.0.6 on 2024-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0010_thesisapply_supervisor_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisapply',
            name='unit_co_approval',
            field=models.BooleanField(default=False),
        ),
    ]
