# Generated by Django 5.0.6 on 2024-05-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0012_remove_thesisapply_unit_co_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisapply',
            name='cv',
        ),
    ]
