# Generated by Django 5.0.6 on 2024-05-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_group_delete_group'),
        ('thesis_apply', '0013_remove_thesisapply_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisapply',
            name='applied_student',
        ),
        migrations.AddField(
            model_name='thesisapply',
            name='applied_student',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
