# Generated by Django 5.0.6 on 2024-05-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_apply', '0014_remove_thesisapply_applied_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisapply',
            old_name='applied_student',
            new_name='applied_students',
        ),
    ]
