# Generated by Django 5.0.6 on 2024-05-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0003_conversation_read_users'),
        ('unit_co', '0002_unitcoordinator_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unit_co',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unit_co.unitcoordinator'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
