# Generated by Django 5.0.6 on 2024-05-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_unit_co_alter_conversation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
