# Generated by Django 5.0.6 on 2024-05-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_conversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_title',
            field=models.CharField(max_length=255),
        ),
    ]
