# Generated by Django 5.0.6 on 2024-05-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisor', '0001_initial'),
        ('unit_co', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.supervisor')),
                ('unit_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_co.unitcoordinator')),
            ],
        ),
    ]
