# Generated by Django 5.0.6 on 2024-05-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(blank=True, to='student.student'),
        ),
    ]
