# Generated by Django 5.0.6 on 2024-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
