# Generated by Django 5.0.6 on 2024-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_max_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='unit_coordinator',
        ),
        migrations.AddField(
            model_name='project',
            name='unit_co_approved',
            field=models.BooleanField(default=False),
        ),
    ]
