# Generated by Django 5.0.6 on 2024-05-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_group_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.IntegerField(default=0),
        ),
    ]
